---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redhat-taro-9-app
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/rhdh-skitamura-org/redhat-taro-9.git 
    targetRevision: main
    path: ./manifest/kustomize/app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sc-demo-test-25
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
  resourceCustomizations: |
    '*':
      labels:
        createBy: rhdh-goldenpath
  ignoreDifferences:
  - kind: ServiceAccount
    jsonPointers:
    - /imagePullSecrets
    - /secrets
