apiVersion: batch/v1
kind: Job
metadata:
  name: redhat-taro-9-webhook-job
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: create-webhook
        command:
          - /bin/bash
          - '-c'
          - |
            set -x
            ansible-playbook -i localhost /scripts/playbook.yaml 
        image: quay.io/agnosticd/ee-multicloud:latest
        volumeMounts:
          - mountPath: /scripts
            name: script-vol
          - mountPath: /secrets/env.yml
            name: webhook
            subPath: env.yml
      restartPolicy: Never
      volumes:
      - name: script-vol
        configMap:
          name: redhat-taro-9-webhook-playbook
      - name: webhook
        secret:
          secretName: github-webhook
